In [1]:
import numpy as np

In [6]:
#create array
a =np.array([1,2,3,4,5])

print(a)
print(type(a))

#Shape means dimension
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [9]:
b= np.array([[1],[2],[3],[4],[5]])
print(b)
print(type(b))
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
<class 'numpy.ndarray'>
(5, 1)


In [18]:
c = np.array([[1,2,3] ,[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])


[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [33]:
#Create array of zeros and ones
a =np.zeros((3,3))
print(a)

b= np.ones((2,3))
print(b)

#Array of constants
c= np.full((3,2), 5)
print(c)

#Identity matrix
d =np.eye(4)
print(d)

#Random matrix
e =np.random.random((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.37187816 0.68651542 0.37407373]
 [0.16455275 0.34858038 0.24028699]]


In [35]:
print(e[:,1])

[0.68651542 0.34858038]


In [37]:
e[1,1:3] =1
print(e)

[[0.37187816 0.68651542 0.37407373]
 [0.16455275 1.         1.        ]]


In [46]:
##SEt some rows and columns
z=np.zeros((3,3) ,dtype=np.int64)
print(z)
z[1,:]=5
print(z)
z[:,-1] =7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [5 5 5]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [47]:
#Datatypes
print(z.dtype)

int64


In [48]:
#mathematical operations

In [54]:
x= np.array([[1,2],[3,4]])
y= np.array([[5,6],[7,8]])

#Element wise addition
print(x+y)
print(np.add(x,y))
print(np.subtract(x,y))


[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [55]:
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]


In [56]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [57]:
# Matrix Multiplication and Dot products

In [59]:
print(x)
print(y)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [61]:
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [63]:
#Multiplication of vectors will give scalar
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(np.dot(a,b))

30


In [64]:
print(a)

[1 2 3 4]


In [65]:
print(sum(a))

10


In [68]:
print(np.sum(a))
print(np.sum(x,axis =0))

10
[4 6]


In [92]:
# Stacking of arrays
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])

In [96]:
print(a)
b=b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [101]:
c= np.stack((a,b),axis=0)

In [102]:
#Reshape a Numpy array
print(c)

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [105]:
 c= c.reshape((4,2))
print(c)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]
