In [1]:
import numpy as np

In [2]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [4]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.arange(2,10,1)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.linspace(1,10,2)

array([ 1., 10.])

In [7]:
np.linspace(2,4,8)

array([2.        , 2.28571429, 2.57142857, 2.85714286, 3.14285714,
       3.42857143, 3.71428571, 4.        ])

In [8]:
np.logspace(2,4,8)

array([  100.        ,   193.06977289,   372.75937203,   719.685673  ,
        1389.49549437,  2682.69579528,  5179.47467923, 10000.        ])

In [12]:
np.random.rand(2,2,2)

array([[[0.85649209, 0.5549708 ],
        [0.41419651, 0.87506218]],

       [[0.81334286, 0.16757058],
        [0.39196289, 0.67043301]]])

In [18]:
np.random.randint(0,10,size=(5,5))

array([[6, 1, 2, 5, 3],
       [7, 6, 6, 8, 8],
       [1, 5, 2, 0, 9],
       [0, 2, 9, 0, 0],
       [8, 3, 0, 9, 2]])

In [20]:
d[:,:]

array([[3, 6, 5, 0, 0],
       [1, 6, 8, 0, 9],
       [8, 0, 8, 8, 8],
       [6, 2, 9, 8, 2],
       [4, 7, 1, 1, 3]])

In [21]:
d[: , 1:2]

array([[6],
       [6],
       [0],
       [2],
       [7]])

In [22]:
d[1:4 , 1:4]

array([[6, 8, 0],
       [0, 8, 8],
       [2, 9, 8]])

In [23]:
#Cocatenation

In [24]:
a= np.zeros((2,2))

In [25]:
b = np.ones((2,2))

In [26]:
a

array([[0., 0.],
       [0., 0.]])

In [27]:
b

array([[1., 1.],
       [1., 1.]])

In [30]:
np.concatenate([a,b])    #axis 0 means be default vertical

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [31]:
np.concatenate([a,b] ,axis=1)    # axis 1 means horizontal

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [32]:
np.vstack([a,b])        #vertically stackin

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [33]:
np.hstack([a,b])       #horizontally stackin

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [34]:
#Splitting

In [37]:
d= np.random.rand(4,4)

In [38]:
d

array([[0.79654527, 0.24271896, 0.08335044, 0.38085447],
       [0.32971966, 0.8590531 , 0.01611771, 0.54338379],
       [0.33076741, 0.89702274, 0.0626676 , 0.29757169],
       [0.09398321, 0.98619903, 0.48535528, 0.69650948]])

In [39]:
d.vsplit(d,[2])         #vertically splitting

AttributeError: 'numpy.ndarray' object has no attribute 'vsplit'

In [50]:
d.hsplit(d,[2])     #horizontal splitting

AttributeError: 'numpy.ndarray' object has no attribute 'hsplit'

In [41]:
# shape, size , ndim

In [42]:
a = np.zeros((2,2))


In [43]:
a

array([[0., 0.],
       [0., 0.]])

In [44]:
a.ndim    #1,D 2,D , 3D

2

In [45]:
a.shape   # Dimensions of array

(2, 2)

In [47]:
a.size    # no. of elements in array

4

In [51]:
# Reshaping

In [52]:
d = np.array([1,2,3,4,5,6,7,9])


In [53]:
d

array([1, 2, 3, 4, 5, 6, 7, 9])

In [54]:
d.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [9]])

In [56]:
d.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 9]])

In [60]:
a= np.array([1,2,3,4,5,6,7,8])


In [63]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
a.reshape(-1,2)    #here 2 means columns are 2 and -1 means derive the number of rows

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [65]:
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [66]:
# Utility Functions

In [67]:
a= np.array([1,2,3,4,5,6])

In [68]:
a

array([1, 2, 3, 4, 5, 6])

In [69]:
np.sum(a)

21

In [70]:
np.max(a)

6

In [71]:
a=np.random.randint(1,100,size=(6,6))

In [72]:
a

array([[65, 84, 17, 15, 50, 39],
       [80, 20, 13, 23, 63, 16],
       [81, 60,  8, 38, 93,  2],
       [69, 81, 78, 25, 36, 43],
       [77, 29, 72, 43, 75, 25],
       [63, 40, 26, 81, 95, 76]])

In [73]:
np.sum(a,axis=0)     # axis =0 sum 

array([435, 314, 214, 225, 412, 201])

In [74]:
np.sum(a,axis=1)    #axis=1 vertically

array([270, 215, 282, 332, 321, 381])

In [75]:
np.sum(a)

1801

In [82]:
#Broadcasting (must condition is either one dimension is to be  1 or empty)

In [77]:
a= np.array([1,2,3,4,5])

In [78]:
b= np.array([3,4,5,7,6])

In [79]:
a+b

array([ 4,  6,  8, 11, 11])

In [80]:
a+6

array([ 7,  8,  9, 10, 11])

In [81]:
np.arange(3).reshape((3,1)) + np.arange(3)   #important example

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])