In [1]:
import numpy as np

In [2]:
#NUMPY RANDOM MODULE

In [4]:
a= np.arange(10) +5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [30]:
np.random.shuffle(a)
a

array([[ 1.5827523 , -1.04514683,  0.25759352],
       [-1.9593946 , -1.50780766, -0.31529207]])

In [22]:
a= np.random.rand(2,3)
print(a)

[[0.99718481 0.93255736 0.12812445]
 [0.99904052 0.23608898 0.39658073]]


In [23]:
#Returns value from standard normal distribution
a= np.random.randn(2,3)
print(a)

[[ 1.5827523  -1.04514683  0.25759352]
 [-1.9593946  -1.50780766 -0.31529207]]


In [16]:
#(x,y,z) : Returns z numbers which are in range x to y
a= np.random.randint(2,8,2)
print(a)

[7 3]


In [17]:
#randomly pick one element
element = np.random.choice([1,4,3,2,11,27])

In [18]:
print(element)

4


In [31]:
# -----------------------STATISTICS IN NUMPY------------------

In [32]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [34]:
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [41]:
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

1
[1 2 3 4]
[1 5]


In [45]:
 #Mean means average of all
b= np.array([1,2,3,4,5])
m= np.sum(b)/5
print(m)

3.0


In [46]:
b= np.array([1,2,3,4,5])
m= np.mean(b)
print(m)

3.0


In [47]:
#Median
c= np.array([1,5,4,2,0])
print(np.median(c))

2.0


In [51]:
#Mean vs Average
print(np.mean(c))
w=np.array([1,2,3,4,5])
print(np.average(c,weights=w))

2.4
2.066666666666667


In [52]:
# Standard deviation

In [54]:
deviation  =np.std(c)
print(deviation)

1.854723699099141


In [55]:
#Variance 
print(np.var(c))

3.4400000000000004
