In [77]:
!pip install word2number
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
from word2number import w2n

# LR for multivariate 


In [3]:
data  = pd.read_csv("homepricesupdated.csv")
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

##### For missing value and dataset cleaning we will do 
##                                    PREPROCESSING


In [6]:
data.bedrooms

0    3.0
1    4.0
2    NaN
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [12]:

preprocessed_data = data.bedrooms.median()

In [14]:
data.bedrooms = data.bedrooms.fillna(preprocessed_data)

In [15]:
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

# LR model training

In [16]:
reg= linear_model.LinearRegression()

In [18]:
reg.fit(data[['area', 'bedrooms', 'age']], data.price)

LinearRegression()

In [20]:
reg.predict([[3000, 3 , 40 ]])

array([498408.25158031])

In [21]:
reg.coef_


array([  112.06244194, 23388.88007794, -3231.71790863])

In [23]:
reg.intercept_

221323.00186540408

In [24]:
3000*112.06244194 + 3*23388.88007794 +40*-3231.71790863 + 221323.00186540408

498408.2515740241

In [25]:
reg.predict([[2500, 4 , 5 ]])

array([578876.03748933])

In [26]:
#---------------------------------end----------------------------------

# Exercise question

In [28]:
info = pd.read_csv('hiring.csv')
info

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [38]:

info.columns =['experience' , 'test_score' , 'interview_score', 'salary']
info.columns

Index(['experience', 'test_score', 'interview_score', 'salary'], dtype='object')

# PREPROCESSING

In [65]:
info.experience= info.experience.fillna("zero")
info.experience

0      zero
1      zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [72]:
updated = info.test_score.mean()
updated

8.0

In [75]:
info.test_score= info.test_score.fillna(updated)


In [78]:
info.experience = info.experience.apply(w2n.word_to_num)
info

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         8.0                7   60000
3           2         8.0               10   65000
4           7         8.0                6   70000
5           3         8.0               10   62000
6          10         8.0                7   72000
7          11         8.0                8   80000

# LR Model Training

In [79]:
reg = linear_model.LinearRegression()

In [82]:
reg.fit(info[['experience', 'test_score' ,'interview_score']] ,info.salary)


LinearRegression()

In [84]:
reg.predict([[2,9,6]])

array([51235.87474472])